# Site Settings
# 
name: Shazib Huaain
title: "Shazib Hussain | Full Stack Software Engineer"
email: contact@shazib.com
description: "Full stack software engineer delivering performant and native experiences."
baseurl: ""
url: "http://shazib.com"
logo: "assets/images/logo.png"
twitter: "@shazibhussain"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "TODO.md"

keep_files:
  - "CNAME"
  - ".gitignore"

